name: kalman_reconstruction
channels:
  - conda-forge
dependencies:
  # Required for full project functionality (dont remove)
  - pytest
  # Examples (remove and add as needed)
  - jupyter
  - jupyterlab
  - numpy
  - scipy
  - scikit-learn
