name: kalman_reconstruction
channels:
  - conda-forge
dependencies:
  # Required for full project functionality (dont remove)
  - pytest
  # Examples (remove and add as needed)
  - pip
  - numpy
  - scipy
  - pandas
  - xarray
  # Jupyter
  - jupyter
  - jupyterlab
  - scikit-learn
  - matplotlib
  - seaborn
  - tqdm
