name: test_env_kalman-reconstruction-partially-observered-systems
channels:
  - conda-forge
dependencies:
  - python=3.10
  ############## These will have to be adjusted to your specific project
  - numpy
  - scipy
  - pandas
  ##############
  - pytest
  - pip:
      - codecov
      - pytest-cov
      - coverage[toml]
      - scikit-learn
