name: kalman_reconstruction_docs
dependencies:
   - python=3.10
   # If your docs code examples depend on other packages add them here
   - numpy
   - scipy
   - pandas
   - xarray
   - scikit-learn
   - tqdm
   # These are needed for the docs themselves
   - numpydoc
   - sphinx
   - sphinx_rtd_theme
   - ipython
   - nbconvert
   - nbformat
   - ipykernel
   - pandoc
   - pip
   - pip:
     - docrep<=0.2.7
     - nbsphinx
     - jupyter_client
     - sphinx_pangeo_theme
     - sphinx-copybutton
     - pydata-sphinx-theme
     - sphinxcontrib-srclinks
     # If fails, also install the package itself
    #  - "git+https://github.com/nilsnevertree/kalman-reconstruction-partially-observed-systems"
